# Generated by Django 6.0.5 on 2026-05-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='ultimo_ingreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
