# Generated by Django 6.0.5 on 2026-06-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0002_alumno_ultimo_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='Ingresos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='MontoDeuda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
