# Generated by Django 6.0.6 on 2026-06-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0003_alter_alumno_ingresos_alter_alumno_montodeuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='DNI',
            field=models.IntegerField(unique=True),
        ),
    ]
