# Generated by Django 6.0.6 on 2026-06-13 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumno', '0002_alumno_ultimo_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('fecha_reclamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='Alumno.alumno')),
            ],
        ),
    ]
