# Generated by Django 6.0.6 on 2026-06-13 02:10
# Generated by Django 6.0.5 on 2026-06-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('clases', models.ManyToManyField(related_name='profesores', to='Clase.clase')),
            ],
        ),
    ]
