# Generated by Codex on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clase', '0001_initial'),
        ('Profesor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='clases',
            field=models.ManyToManyField(blank=True, related_name='profesores', to='Clase.clase'),
        ),
    ]
