# Generated by Codex on 2026-06-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0003_alter_alumno_ingresos_alter_alumno_montodeuda'),
        ('Profesor', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alumno',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='usuario',
                to='Alumno.alumno',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='profesor',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='usuario',
                to='Profesor.profesor',
            ),
        ),
    ]
