# Generated by Django 6.0.6 on 2026-06-13 02:10
# Generated by Django 6.0.5 on 2026-06-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumno', '0002_alumno_ultimo_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dias', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('alumnos', models.ManyToManyField(related_name='clases', to='Alumno.alumno')),
            ],
        ),
    ]
